import LIBS = lib{pulmotor} doctest%lib{doctest} nanobench%lib{nanobench}

for f: cxx{**.tests...}
{
	d=$directory($f)
	n=$name($f)...
	./: exe{$n}: $f $LIBS testscript{+$n}
}

#./: exe{pulmotor_tests}

