#config.import.doctest1=../../../../stir.git/externals/b_doctest

doctest/
{
	lib{doctest}: doctest/hxx{doctest.h}
	{
		cxx.export.poptions = "-I$src_base/doctest"
	}
}

import LIB = lib{pulmotor}

#exe{pulmotor_tests}: cxx{*.tests...} doctest/lib{doctest} $LIB

for f: cxx{**.tests...}
#for f: cxx{archive.tests...} cxx{stream.tests...}
{
	d=$directory($f)
	n=$name($f)...
	./: exe{$n}: $f doctest/lib{doctest} $LIB testscript{+$n}
}

#./: exe{pulmotor_tests}

